apiVersion: v1
kind: Service
metadata:
  name: charge-details-service
  labels:
    app: charge-details-service
spec:
  type: NodePort
  selector:
    app: charge-details-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080